### ISSUE TITLE
Уrror when clicking on the buttons "Categories", "Reset", "SaveTemplate", "LoadTemplate".

### ISSUE THREAD

**Issue by Osert** [Luxocracy/TidyPlates_BFA#2]
Message: Interface\AddOns\TidyPlatesHub\Templates.lua:620: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: Mon Jul 23 21:30:06 2018
Count: 2
Stack: Interface\AddOns\TidyPlatesHub\Templates.lua:620: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
Interface\AddOns\TidyPlatesHub\Templates.lua:620: in function <Interface\AddOns\TidyPlatesHub\Templates.lua:619>

Locals: (*temporary) = "igMainMenuOptionCheckBoxOn"

**Comment by Luxocracy** [comment]
This should now be working. This was due to an older bug(probably since around the launch of Legion) that I though was already fixed but apparently some places were missed.
